package com.outleap.scholar.distributed.lock

import org.springframework.stereotype.Component

@Component
class ConcurrencyHelper {

    fun getLockKey(context: ConcurrencyContext, userId: Any) = "${context.prefix}_$userId"
}

enum class ConcurrencyContext(val prefix: String) {
    PURCHASE_BUNDLE("PURCHASE_BUNDLE"),
    CONSUME_PRODUCT("CONSUME_PRODUCT"),
    ZOHO_LEAD_API("ZOHO_LEAD_API"),
    CREATE_ZOHO_LEAD_API("CREATE_ZOHO_LEAD_API"),
    MASTERCLASS_SUBSCRIPTION("MASTERCLASS_SUBSCRIPTION"),
    MASTERCLASS_REGISTRATION("MASTERCLASS_REGISTRATION"),
    STUDENT_INFO("STUDENT_INFO"),
    COURSE_FINDER("COURSE_FINDER"),
    ZOHO_APPLICATION("ZOHO_APPLICATION"),
    APPLICATION_STATUS_CHANGE("APPLICATION_STATUS_CHANGE"),
    COUNSELLING_STAGE_CHANGE("COUNSELLING_STAGE_CHANGE"),
    STUDENT_DOCUMENT("STUDENT_DOCUMENT"),
    APPLICATION_DOCUMENT("APPLICATION_DOCUMENT"),
    BETA_FEATURE("BETA_FEATURE"),
    ZOHO_TOKEN("ZOHO_TOKEN"),
    GB_AGGREGATOR("GB_AGGREGATOR"),
    EDUCATION_FINANCING("EDUCATION_FINANCING"),
    INTERNAL_TICKET("INTERNAL_TICKET")
}